[package]
name = "PasswordManager"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
aes-gcm = "0.10.3"
base64 = "0.22.1"
egui = "0.28.1"
eframe = "0.28.1"
sha2 = "0.11.0-pre.3"
rfd = "0.14.1"  # Añade esta línea